### ISSUE TITLE
gitlab support

### ISSUE THREAD

**Issue by offthegrass** [DispatchMe/mgp#10]
how easy would it be to use gitlab with this?

**Comment by jperl** [comment]
IDK --- happy to accept PRs though

**Comment by bitomule** [comment]
Yeah, gitlab support would be great. I think gitlab allows getting tar from repo but not sure how to do it with private repos.

**Comment by heschong** [comment]
Non-private gitlab tarball URLs are in this format:

http://[your_gitlab_url]/[package_path]/repository/archive.tar.gz

Two problems:

1) A lot of gitlab instances (at least mine) are using ssl certs signed by private CAs, and mgp throws an error when hitting an untrusted cert.  Maybe that should be a separate issue.

2) Private repositories require a login, and HTTP basic auth doesn't work.

Is there any reason mgp only works with tarballs and not via a git clone over ssh?

**Comment by jperl** [comment]
It should be refactored to use a git clone over ssh. Unfortunately I have not had the time to refactor it.

**Comment by jperl** [comment]
We are moving away from tarballs to using pure git. So this will be fixes in #19

**Comment by jperl** [comment]
Please check on `v1.0.0` gitlab should now be supported.
