### ISSUE TITLE
Unable to load file

### ISSUE THREAD

**Issue by Kielan** [DispatchMe/mgp#11]
I seem to be unable to laod file with either mgp or mgp link. 

I am playing around under the hood and am now logging the error type as getting the same error:
SyntaxError: Unexpected token /

Any thoughts on where this is coming from.

**Comment by aldeed** [comment]
@Kielan what OS?

**Comment by Kielan** [comment]
OSX Yosemite

**Comment by aldeed** [comment]
Works for me on same OS. Maybe check your JSON files to make sure they're valid JSON.

**Comment by jperl** [comment]
I just released the latest `devel` which is more lenient on invalid files. Not sure if it will help.

**Comment by jperl** [comment]
Is this still an issue?

**Comment by jperl** [comment]
Please let me know if you still run into it.
