### ISSUE TITLE
Add definition of package by git tag to docs

### ISSUE THREAD

**Issue by kahmali** [DispatchMe/mgp#15]
See this comment: https://github.com/DispatchMe/mgp/issues/13#issuecomment-109374765.

**Comment by jperl** [comment]
That is a feature of famono -- not mgp.

**Comment by jperl** [comment]
(Not to say we shouldn't add that functionality -- as part of #9)

**Comment by kahmali** [comment]
Oh sorry, I misunderstood @raix's comment. I agree, this will just be a part of #9.
