### ISSUE TITLE
Supply token as an environment variable

### ISSUE THREAD

**Issue by petermikitsh** [DispatchMe/mgp#17]
I'm not putting that in my codebase. Or is the intended usage to gitignore `git-packages.json`? The disadvantage to gitignoring would be having to regenerate the json file on each fresh clone of the repo.

**Comment by aldeed** [comment]
Should be resolved by #9

**Comment by petermikitsh** [comment]
Thanks, I missed that when looking through the issues. It might be a good idea to update the README and recommend this approach.

**Comment by jperl** [comment]
We are moving away from tarballs to using pure git. So this will be fixed in #19
