### ISSUE TITLE
Improve local development support

### ISSUE THREAD

**Issue by jperl** [DispatchMe/mgp#2]
For local development it would be nice to symlink to local packages

`mgp link local-packages.json`

local-packages.json

````
{
  "your:private-package": {
    "path": "path-to-symlink-to"
  },
  "your:other-private-package": {
    "path": "path-to-symlink-to"
  }
}
````

**Comment by raix** [comment]
looks good :)

**Comment by jperl** [comment]
@raix Should this support tarballs as well.

````
{
  "your:private-package": {
    "path": "path-to-symlink-to"
  },
  "your:other-private-package": {
    "tarball": "https://api.github.com/repos/your/private-package/tarball/commithash",
    "path": "path-to-package"
  }
}
````

**Comment by jperl** [comment]
Also maybe it makes more sense to combine the two --- and only have one command `mgp`?

**Comment by aldeed** [comment]
I like the idea of a single command. Maybe look for the same file name but with `-local` and use those as local symlink overrides?

**Comment by aldeed** [comment]
I think my goal would be to be able to swap between tarball/symlink with a single command. Generally I'd use symlinking locally, but sometimes you want to do a quick test to make sure it's pulling in the correct tarballs.

**Comment by jperl** [comment]
@aldeed We should bump versions on the private packages -- that way meteor's semantic analysis will catch mistakes.

**Comment by jperl** [comment]
Since you want to switch between tarball/symlink I think it should be a separate command `mgp link`, which will look at `local-packages.json`

**Comment by aldeed** [comment]
@jperl, `mgp link` sounds good as long as we can alternate between the commands without a mess.

Re version bumps: so once done making some package changes, we

1. bump version, commit, and push
2. grab the new commit ref and update mgp json in meteor-cache (or wherever used)
3. update .meteor/packages in meteor-cache (or wherever used) with latest version
4. commit 2 & 3

Right?

**Comment by jperl** [comment]
Yep. It's kinda a hassle -- which is why it would be nice to publish to our [own package server](https://github.com/meteor/meteor/issues/3893#issuecomment-90202945).

**Comment by raix** [comment]
We could also use our own track of meteor and simply add the feature via a node package - making it easier to maintain. Much like isohouse https://github.com/raix/Meteor-include

**Comment by jperl** [comment]
Yeah and we could try to submit a PR to meteor core. The bundler is so scary though.

**Comment by raix** [comment]
I've been down that road before, it's not too bad - but could have been much better modulized
