### ISSUE TITLE
Nested dependencies

### ISSUE THREAD

**Issue by ChJJin** [DispatchMe/mgp#25]
I think it should consider the situation if the package has its own ```git-packages.json``` file which means it relies on other private packages.

**Comment by jperl** [comment]
This is certainly a welcome enhancement -- that would probably require a bit of work. If anyone is wondering how to do this now, just add all of the private dependencies at the root level `git-packages.json`.

**Comment by jperl** [comment]
Closing -- in favor of switching to private npm packages with meteor 1.3.
