### ISSUE TITLE
Add safe mode

### ISSUE THREAD

**Issue by backsapce** [DispatchMe/mgp#26]
i think mgp can add a featrue. like safe mode.when you use mgp to refresh you package form git repo. if you had changed you some file in package.then alert " do you want to cover the changed file?".so this can give user the chance to stop the silly action to cover their code.
for examle:
```js
mgp -s //run in safe mode then alert user when  some  file had changed.
```
if you don't mind ,i can implement it and send a  PULL REQUEST.

one time.i write some code in package and debug it.then i take a rest .when i come back.take a mistake to run mgp!!! so my code lost.i just wana to cut off my FUCKing finger.

**Comment by jperl** [comment]
We would love a pull request. Good idea!

**Comment by yjzar** [comment]
lol

**Comment by raix** [comment]
maybe have `mgp -f` instead to force a potentially breaking update and assume the user wants to be safe pr. default.

**Comment by jperl** [comment]
Closing for now. Happy to entertain PRs.
