### ISSUE TITLE
Documentation for .netrc auth

### ISSUE THREAD

**Issue by rhyslbw** [DispatchMe/mgp#29]
Any chance you can document the way you authenticate with .netrc? @jraede on the Meteor Club Podcast mentioned a special read-only user being created and access being granted to specific repos. Is this a GitHub Organisation feature? If on a personal plan, would a [personal access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) achieve the same result?

**Comment by jperl** [comment]
Hi @rhyslbw I added a link to an example .netrc file https://gist.github.com/jperl/91f32a37dc1c12c48ad8

We setup a github account and create a special team that only has read access to the relevant repos --- but a personal access token should work as well.

Let me know if you still have any questions.

**Comment by rhyslbw** [comment]
Thanks @jperl . When looking at the code more closely I can see the toHttps implementation is [tied to GitHub](https://github.com/DispatchMe/mgp/blob/master/packages.js#L213), which meant my BitBucket URLs were being ignored with just a generic clone failure error. I've submitted https://github.com/DispatchMe/mgp/pull/30 to address this, but as you can see the build is failing in a place I can't test locally due to the creds being stored on the build server. I included unit tests for the changes which were passing on my machine, so if you can take a look it would be much appreciated

**Comment by jperl** [comment]
I tried to clone that repo locally but was unable --- so I would guess the build is failing since CI does not have access either.

![](https://s3.amazonaws.com/f.cl.ly/items/0K3Y18180e1r0S1k0F2J/Screen%20Shot%202015-09-29%20at%2010.32.38%20AM.png)

**Comment by rhyslbw** [comment]
I've only defined those packages in the toHttps unit test, so it shouldn't be called elsewhere
