### ISSUE TITLE
Authentication to run tests locally

### ISSUE THREAD

**Issue by rhyslbw** [DispatchMe/mgp#31]
It would be great if I could run the test suite locally so I can contribute more. Is there a security issue I'm overlooking putting an SSH key that has no access to a testing private repo in the mgp package?

**Comment by raix** [comment]
Hi Rhys,

Yeah I think that could be it - but I think you should be able to replace the repo in the test with your own secret repo - but you would have to recreate the folders/files checked by the test.

**Comment by rhyslbw** [comment]
Thanks @raix.

@jperl is there an issue with putting a read-only access SSH key to DispatchMe/mgp-private-package-test.git in this repo and use that when running the tests?

**Comment by rhyslbw** [comment]
Thanks @jperl
