### ISSUE TITLE
Specify branch

### ISSUE THREAD

**Issue by rhyslbw** [DispatchMe/mgp#32]
I'm feeling the need to be riding the develop branch during the initial development phase of a project. Have you considered this as an option, and if so what are your thoughts? I did have a look at modifying, but I'm hesitant since there are a few refactors needed and I can't run tests 
https://github.com/DispatchMe/mgp/issues/31.

**Comment by raix** [comment]
it would be nice to do `mgp branch=dev` - but this would only be applied repos not already fixed on a commit right?

**Comment by rhyslbw** [comment]
I was thinking more just as an alternative to 'version':

{
  "my:private-package": {
    "git": "git@github.com:my/private-packages.git",
    "branch": "develop",
    "path": "optional/directory/path"
  }
}

**Comment by rhyslbw** [comment]
Any thoughts on this @jperl ?

**Comment by sokki** [comment]
@rhyslbw if you dont provide a version, mgp loads the current HEAD. You can change your default branch in github to `dev`. If you do so, you only need to specify the version for production deploy.

**Comment by rhyslbw** [comment]
Thanks @sokki, however really we're finding the need to be pegging a feature branch on a dependant repo.

**Comment by jperl** [comment]
Thanks for the PR -- I'll check it out tonight. FYI the tests only work on travis when I run them, because it only adds the private key then.
