### ISSUE TITLE
Explain why copying doesn't happen

### ISSUE THREAD

**Issue by aldeed** [DispatchMe/mgp#5]
When I run the `mgp` command multiple times, sometimes it removes the packages, doesn't do anything, or adds packages. I'm guessing maybe it's failing silently when there are network issues? But there isn't any logging to explain what's happening, so that might be a good first step. Display a message if folder is not copied for some reason.

@jperl

**Comment by aldeed** [comment]
It's possible it chokes on the colons in the package folder names. I seem to recall that OSX doesn't technically support colons in a folder name, though it kind of works in most cases. There was a debate about it when Meteor did their packaging system. Might be good to replace with an underscore or dash.

**Comment by Kielan** [comment]
Any Update on this issue?

**Comment by aldeed** [comment]
@Kielan has been working fine since the fix.
