### ISSUE TITLE
Make it work with .netrc

### ISSUE THREAD

**Issue by jperl** [DispatchMe/mgp#9]
This way people do not need to expose a github token in the config.

https://gist.github.com/technoweenie/1072829

**Comment by jperl** [comment]
If we move off of using tarballs -> git, it would allow other services such as gitlab. See #10

**Comment by creeonix** [comment]
https://github.com/jazzdev/node-netrc

**Comment by aldeed** [comment]
I wasn't sure if this way would work with the deploy scripts.

**Comment by creeonix** [comment]
It will, we made it work on semaphore. just place .netrc in the ~/ 
If CI cannot provide you isolated environment, it should not be used at all.

**Comment by jperl** [comment]
We are moving away from tarballs to using pure git. So this will be fixes in #19
